= ERC 721

This set of interfaces, contracts, and utilities are all related to the `ERC721` Non-Fungible Token Standard.

NOTE: For an overview of ERC20 tokens and a walkthrough on how to create a token contract, read our ERC20 guide.

For a walkthrough on how to create an `ERC721` token read our `ERC721` guide.

The EIP consists of three interfaces, found here as `IERC721`, `IERC721Metadata`, and `IERC721Enumerable`. Only the first one is required in a contract to be ERC721 compliant.

Each interface is implemented separately in `ERC721`, `ERC721Metadata`, and `ERC721Enumerable`. You can choose the subset of functionality you would like to support in your token by combining the desired subset through inheritance.

The fully featured token implementing all three interfaces is prepackaged as `ERC721Full`.

Additionally, `IERC721Receiver` can be used to prevent tokens from becoming forever locked in contracts. Imagine sending an in-game item to an exchange address that can't send it back!. When using safeTransferFrom(), the token contract checks to see that the receiver is an `IERC721Receiver`, which implies that it knows how to handle `ERC721` tokens. If you're writing a contract that needs to receive ERC721 tokens, you'll want to include this interface.

Finally, some custom extensions are also included:

* `ERC721Mintable` — like the ERC20 version, this allows certain addresses to mint new tokens
* `ERC721Pausable` — like the ERC20 version, this allows addresses to freeze transfers of tokens

WARNING: This page is incomplete. We're working to improve it for the next release. Stay tuned!

== Core

=== IERC721
Interface of the ERC20 standard as defined in the EIP. Does not include the optional functions; to access them see ERC20Detailed.

[.description]
.Functions
----
balanceOf(address owner)
ownerOf(uint256 tokenId)
safeTransferFrom(address from, address to, uint256 tokenId)
transferFrom(address from, address to, uint256 tokenId)
approve(address to, uint256 tokenId)
getApproved(uint256 tokenId)
setApprovalForAll(address operator, bool _approved)
isApprovedForAll(address owner, address operator)
safeTransferFrom(address from, address to, uint256 tokenId, bytes data)
supportsInterface(bytes4 interfaceId)
----

[.description]
.Events
----
Transfer(address from, address to, uint256 tokenId)
Approval(address owner, address approved, uint256 tokenId)
ApprovalForAll(address owner, address operator, bool approved)
----

[.function]
.ownerOf(address owner) → [secondary]`uint256` [function__type]#public#
****
	Returns the number of NFTs in owner's account.
****

[.function]
.balanceOf(address owner) → [secondary]`uint256` [function__type]#public#
****
	Returns the number of NFTs in owner's account.
****

[.function]
.transferFrom(address owner) → [secondary]`uint256` [function__type]#internal#
****
	Returns the number of NFTs in owner's account.
****

[.function]
.setApprovalForAll(address owner) → [primary]`bool` [function__type]#private#
****
	Transfers a specific NFT (tokenId) from one account (from) to another (to).

	Requirements:
	* from, to cannot be zero.
	* tokenId must be owned by from.
	* If the caller is not from, it must be have been allowed to move this NFT by either approve or setApproveForAll.
****

== Extensions

=== IERC721
Interface of the ERC20 standard as defined in the EIP. Does not include the optional functions; to access them see ERC20Detailed.

[.description]
.Functions
----
balanceOf(address owner)
ownerOf(uint256 tokenId)
safeTransferFrom(address from, address to, uint256 tokenId)
transferFrom(address from, address to, uint256 tokenId)
approve(address to, uint256 tokenId)
getApproved(uint256 tokenId)
setApprovalForAll(address operator, bool _approved)
isApprovedForAll(address owner, address operator)
safeTransferFrom(address from, address to, uint256 tokenId, bytes data)
supportsInterface(bytes4 interfaceId)
----

[.description]
.Events
----
Transfer(address from, address to, uint256 tokenId)
Approval(address owner, address approved, uint256 tokenId)
ApprovalForAll(address owner, address operator, bool approved)
----

[.function]
.ownerOf(address owner) → [secondary]`uint256` [function__type]#public#
****
	Returns the number of NFTs in owner's account.
****

[.function]
.balanceOf(address owner) → [secondary]`uint256` [function__type]#public#
****
	Returns the number of NFTs in owner's account.
****

[.function]
.transferFrom(address owner) → [secondary]`uint256` [function__type]#internal#
****
	Returns the number of NFTs in owner's account.
****

[.function]
.setApprovalForAll(address owner) → [primary]`bool` [function__type]#private#
****
	Transfers a specific NFT (tokenId) from one account (from) to another (to).

	Requirements:
	* from, to cannot be zero.
	* tokenId must be owned by from.
	* If the caller is not from, it must be have been allowed to move this NFT by either approve or setApproveForAll.
****

== Convenience

=== IERC721
Interface of the ERC20 standard as defined in the EIP. Does not include the optional functions; to access them see ERC20Detailed.

[.description]
.Functions
----
balanceOf(address owner)
ownerOf(uint256 tokenId)
safeTransferFrom(address from, address to, uint256 tokenId)
transferFrom(address from, address to, uint256 tokenId)
approve(address to, uint256 tokenId)
getApproved(uint256 tokenId)
setApprovalForAll(address operator, bool _approved)
isApprovedForAll(address owner, address operator)
safeTransferFrom(address from, address to, uint256 tokenId, bytes data)
supportsInterface(bytes4 interfaceId)
----

[.description]
.Events
----
Transfer(address from, address to, uint256 tokenId)
Approval(address owner, address approved, uint256 tokenId)
ApprovalForAll(address owner, address operator, bool approved)
----

[.function]
.ownerOf(address owner) → [secondary]`uint256` [function__type]#public#
****
	Returns the number of NFTs in owner's account.
****

[.function]
.balanceOf(address owner) → [secondary]`uint256` [function__type]#public#
****
	Returns the number of NFTs in owner's account.
****

[.function]
.transferFrom(address owner) → [secondary]`uint256` [function__type]#internal#
****
	Returns the number of NFTs in owner's account.
****

[.function]
.setApprovalForAll(address owner) → [primary]`bool` [function__type]#private#
****
	Transfers a specific NFT (tokenId) from one account (from) to another (to).

	Requirements:
	* from, to cannot be zero.
	* tokenId must be owned by from.
	* If the caller is not from, it must be have been allowed to move this NFT by either approve or setApproveForAll.
****
